/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JournalUI.java
 *
 * Created on Feb 21, 2010, 5:23:46 PM
 */



/**
 *
 * @author olkin
 */
public class JournalUI extends javax.swing.JFrame {

    /** Creates new form JournalUI */
    public JournalUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        termPanel1 = new TermPanel();
        termPanel2 = new TermPanel();
        originalAnnualResultLabel = new javax.swing.JLabel();
        originalAnnualResultText = new javax.swing.JTextField();
        improvedAnnualResultLabel = new javax.swing.JLabel();
        improvedAnnualResultText = new javax.swing.JTextField();
        calculateAnnualResultBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        termPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Term #1"))));

        termPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Term #2"));

        originalAnnualResultLabel.setText("Original Result:");

        improvedAnnualResultLabel.setText("Improved Result:");

        improvedAnnualResultText.setForeground(new java.awt.Color(235, 16, 16));

        calculateAnnualResultBtn.setText("Calculate Annual Result!");
        calculateAnnualResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateAnnualResultBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(termPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(termPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculateAnnualResultBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(originalAnnualResultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(originalAnnualResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(improvedAnnualResultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(improvedAnnualResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {improvedAnnualResultText, originalAnnualResultText});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(termPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(termPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(originalAnnualResultLabel)
                        .addComponent(calculateAnnualResultBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(originalAnnualResultText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(improvedAnnualResultLabel)
                        .addComponent(improvedAnnualResultText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {improvedAnnualResultText, originalAnnualResultText});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateAnnualResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateAnnualResultBtnActionPerformed
        double originalAnnualAvg = (termPanel1.getOriginalAvgTerm() + termPanel2.getOriginalAvgTerm())/2;
        originalAnnualResultText.setText(TermPanel.getFormattedString(originalAnnualAvg));

        double improvedAnnualAvg = (termPanel1.getImprovedAvgTerm() + termPanel2.getImprovedAvgTerm())/2;
        improvedAnnualResultText.setText(TermPanel.getFormattedString(improvedAnnualAvg));

    }//GEN-LAST:event_calculateAnnualResultBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new JournalUI().setVisible(true);
    }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateAnnualResultBtn;
    private javax.swing.JLabel improvedAnnualResultLabel;
    private javax.swing.JTextField improvedAnnualResultText;
    private javax.swing.JLabel originalAnnualResultLabel;
    private javax.swing.JTextField originalAnnualResultText;
    private TermPanel termPanel1;
    private TermPanel termPanel2;
    // End of variables declaration//GEN-END:variables

}
